### ISSUE TITLE
Allow specifying short node names

### ISSUE THREAD

**Issue by nkinkade** [m-lab/bmctool#2]
Currently, to get DRAC credentials you have to specify the FQDN of the DRAC, which is a lot to type. It would be nice if the `-node` option allowed one to specify something like:

`$ bmctool -node mlab1.den01`

... a short name, and optionally not including the `d`. It should probably accept any of the following and still do the right thing:

* mlab1d.den01.measurement-lab.org
* mlab1.den01.measurement-lab.org
* mlab1d.den01
* mlab1.den01

**Comment by evfirerob** [comment]
The syntax changed a bit since we've moved to cobra for the CLI, but with https://github.com/m-lab/bmctool/pull/13 it's possible to run 

`$ bmctool get mlab1.den01`
`$ bmctool get mlab1d.den01`
